/* Activity + category + age-band + benefit data for the Spark Station generator.
   Pure data — no logic lives here so it stays easy to extend by hand. */

const AGE_BANDS = [
  { id: '3-5', label: '3–5 yrs' },
  { id: '5-7', label: '5–7 yrs' },
  { id: '7-9', label: '7–9 yrs' },
];

const CATEGORIES = [
  { id: 'science',  label: 'Science Discovery', emoji: '🔬', color: '#3E7C82' },
  { id: 'sensory',  label: 'Sensory Play',       emoji: '🌈', color: '#8E5B8C' },
  { id: 'art',      label: 'Art & Craft',        emoji: '🎨', color: '#C97B4A' },
  { id: 'movement', label: 'Movement & Games',   emoji: '🤸', color: '#4C7A3F' },
  { id: 'calm',     label: 'Calm-Down',          emoji: '🫧', color: '#5B6EAE' },
  { id: 'fine',     label: 'Fine Motor',         emoji: '✋', color: '#B0801F' },
  { id: 'social',   label: 'Social-Emotional',   emoji: '💛', color: '#B05A6B' },
];

/* What each activity is helping the child build. Shown on cards and in the
   detail view so the teacher can see (and choose) the goal, not just the task. */
const BENEFITS = [
  { id: 'attention',           label: 'Focus & Attention',        emoji: '🎯', blurb: 'Practices sustaining attention on one thing at a time, in short, achievable bursts.' },
  { id: 'fine-motor',          label: 'Fine Motor Skills',        emoji: '✋', blurb: 'Builds hand strength, grip, and precision used for writing, buttoning, and self-care.' },
  { id: 'gross-motor',         label: 'Gross Motor Skills',       emoji: '🏃', blurb: 'Builds whole-body coordination and burns excess energy in a structured way.' },
  { id: 'sensory-processing',  label: 'Sensory Processing',       emoji: '🌟', blurb: 'Offers controlled sensory input to help the body register and organize touch, sound, or movement.' },
  { id: 'self-regulation',     label: 'Self-Regulation',          emoji: '🧘', blurb: 'Practices calming the body and mind — useful before, during, or after high-stimulation moments.' },
  { id: 'social-emotional',    label: 'Social-Emotional Skills',  emoji: '🤝', blurb: 'Builds turn-taking, empathy, cooperation, and naming feelings.' },
  { id: 'language',            label: 'Language & Vocabulary',    emoji: '💬', blurb: 'Encourages describing, naming, and narrating — growing expressive language.' },
  { id: 'cognitive',           label: 'Thinking & Problem-Solving', emoji: '🧩', blurb: 'Practices predicting, sorting, sequencing, and cause-and-effect reasoning.' },
  { id: 'confidence',          label: 'Confidence & Independence', emoji: '🌱', blurb: 'Gives a clear, reachable win the child can complete and feel proud of on their own.' },
];

const ACTIVITIES = [
  // ---------- SCIENCE ----------
  {
    id: 'sci-01', title: 'Rainbow Walking Water', category: 'science',
    ages: ['5-7', '7-9'], duration: 25, dexterityFriendly: true,
    benefits: ['cognitive', 'attention', 'language'],
    materials: ['6 clear cups', 'Water', 'Red, yellow, blue food coloring', 'Paper towel strips (pre-folded)'],
    setup: 'Line up 6 cups in a circle. Fill every other cup with water and 2–3 drops of one primary color.',
    steps: [
      'Show the empty and full cups and ask kids to predict what will happen.',
      'Place one end of a folded paper towel strip in a full cup, the other end in an empty neighbor cup.',
      'Repeat all the way around so every cup has two strips going into it.',
      'Set a visible timer for 5-minute "check-ins" to watch the color travel.',
      'After 1–2 hours, empty cups fill with blended colors — compare to the predictions.',
    ],
    safety: ['Food coloring stains — use smocks or old shirts', 'Supervise near water to avoid spills/slips'],
    attentionTips: ['The waiting time becomes the game: a 5-minute check-in timer gives restless hands a job', 'Pair with a simple prediction chart so there is something to mark each visit'],
    dexterityNotes: 'Pre-fold the paper towel strips yourself; the child only needs to place the ends into cups.',
  },
  {
    id: 'sci-02', title: 'Baking Soda Volcano', category: 'science',
    ages: ['5-7', '7-9'], duration: 20, dexterityFriendly: true,
    benefits: ['cognitive', 'confidence', 'attention'],
    materials: ['Small plastic bottle', 'Baking soda', 'Vinegar', 'Dish soap (optional, for foam)', 'Tray to contain mess', 'Food coloring (optional)'],
    setup: 'Stand the bottle in the center of a tray. Add 2 tbsp baking soda, a squirt of dish soap, and a few drops of color into the bottle.',
    steps: [
      'Let the child pour vinegar into the bottle a little at a time using a small cup or funnel.',
      'Watch and name the reaction: bubbles, fizzing, color changing.',
      'Repeat 2–3 times, adding more baking soda and vinegar for a second "eruption".',
      'Talk through what happened: baking soda + vinegar makes gas bubbles.',
    ],
    safety: ['Keep vinegar out of eyes; rinse with water if it happens', 'Do on a tray — this activity is intentionally messy'],
    attentionTips: ['The instant, loud reaction gives immediate payoff — great for short attention spans', 'Let the child control the pour speed for a sense of ownership'],
    dexterityNotes: 'Use a funnel and a small measuring cup with a handle so pouring is easier to control.',
  },
  {
    id: 'sci-03', title: 'Sink or Float Sort', category: 'science',
    ages: ['3-5', '5-7'], duration: 15, dexterityFriendly: true,
    benefits: ['cognitive', 'fine-motor', 'language'],
    materials: ['Clear tub of water', '8–10 safe household objects (cork, spoon, leaf, toy car, sponge, coin, crayon, rock)', 'Two labeled bins or hoops ("Sink" / "Float")'],
    setup: 'Fill the tub about half full with water and lay all objects out on a towel nearby.',
    steps: [
      'Hold up one object and ask "sink or float?" before dropping it in.',
      'Drop it in and watch together, then sort it into the matching bin.',
      'Repeat for all objects, letting the child do the dropping and sorting.',
      'Group results together and talk about what floaters have in common (light, hollow, etc.).',
    ],
    safety: ['Wipe the floor around the tub — standing water is a slip hazard', 'Avoid objects with sharp edges'],
    attentionTips: ['One object at a time keeps the task in small, finishable chunks', 'Guessing before dropping turns each item into a mini game'],
    dexterityNotes: 'Use larger, easy-to-grip objects; a slotted spoon lets a child fish items out without needing pincer grip.',
  },
  {
    id: 'sci-04', title: 'Melting Ice Excavation', category: 'science',
    ages: ['3-5', '5-7', '7-9'], duration: 30, dexterityFriendly: true,
    benefits: ['attention', 'fine-motor', 'confidence'],
    materials: ['Large ice block with small toys frozen inside (freeze the night before)', 'Warm water in a squeeze bottle', 'Salt', 'Plastic mallet or spoon (optional)'],
    setup: 'Freeze small plastic animals or gems inside a container of water overnight, then pop the ice block into a tray.',
    steps: [
      'Let the child pour warm water over the ice a little at a time.',
      'Sprinkle salt on stubborn spots and watch it tunnel through the ice.',
      'Use a spoon to gently chip at melted grooves to help free the toys.',
      'Celebrate each toy as it is "rescued".',
    ],
    safety: ['Ice is cold and can numb small hands — offer breaks or gloves', 'Supervise use of the mallet/spoon around the ice'],
    attentionTips: ['Each freed toy is a built-in mini reward that resets attention', 'Great low-pressure activity — there is no wrong way to melt the ice'],
    dexterityNotes: 'A squeeze bottle is easier to control than a jug; salt can simply be sprinkled by hand with no tool needed.',
  },
  {
    id: 'sci-05', title: 'Static Electricity Butterfly', category: 'science',
    ages: ['5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['cognitive', 'attention', 'sensory-processing'],
    materials: ['Tissue paper cut into butterfly shapes', 'Balloon', 'Wool sweater or hair'],
    setup: 'Cut light tissue-paper butterflies ahead of time and lay them on a table.',
    steps: [
      'Rub the balloon on hair or a wool sweater for about 10 seconds.',
      'Slowly bring the balloon close to a tissue-paper butterfly without touching it.',
      'Watch the butterfly "fly" up and stick to the balloon.',
      'Try lifting several butterflies at once and count how many stick.',
    ],
    safety: ['Balloons are a choking hazard if popped — supervise closely, especially with younger kids'],
    attentionTips: ['The "magic" of things moving without touching is highly novel and re-engaging', 'Counting how many butterflies stick adds a simple goal'],
    dexterityNotes: 'Rubbing the balloon is a gross-motor motion, easy for kids with limited fine motor control.',
  },
  {
    id: 'sci-06', title: 'Milk & Soap Color Explosion', category: 'science',
    ages: ['5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['attention', 'sensory-processing', 'fine-motor'],
    materials: ['Shallow dish of whole milk', 'Food coloring (several colors)', 'Dish soap', 'Cotton swab'],
    setup: 'Pour milk into a shallow dish so it just covers the bottom.',
    steps: [
      'Add a few drops of different food colors around the milk without stirring.',
      'Dip a cotton swab in dish soap.',
      'Touch the soapy swab to the center of the milk and watch the colors burst and swirl.',
      'Try touching a few different spots to see new patterns.',
    ],
    safety: ['Do not drink the milk mixture — keep away from very young children who mouth objects'],
    attentionTips: ['Instant, colorful, and repeatable — each new dab creates fresh movement to watch', 'Let the child pick the color order to give a sense of control'],
    dexterityNotes: 'Only one small, controlled motion (touching the swab down) is needed — good for limited hand strength.',
  },
  {
    id: 'sci-07', title: 'Growing Bean in a Bag', category: 'science',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['self-regulation', 'cognitive', 'language'],
    materials: ['Zip-top plastic bag', 'Paper towel', 'Dried lima or pinto bean', 'Water', 'Tape', 'Sunny window'],
    setup: 'Fold a damp paper towel to fit inside the bag.',
    steps: [
      'Place the damp paper towel inside the bag.',
      'Tuck the bean between the towel and the bag, about a third of the way down.',
      'Tape the bag to a sunny window.',
      'Check in for 1 minute each day, drawing or describing what changed.',
    ],
    safety: ['Beans are a choking hazard for children who mouth objects — supervise'],
    attentionTips: ['A daily 1-minute check-in builds a routine kids can anticipate rather than needing sustained focus at once', 'A simple daily drawing log turns waiting into an activity of its own'],
    dexterityNotes: 'Pre-fold the towel; the child just needs to tuck the bean in, a large and forgiving motion.',
  },
  {
    id: 'sci-08', title: 'Balloon Rocket Race', category: 'science',
    ages: ['5-7', '7-9'], duration: 20, dexterityFriendly: false,
    benefits: ['cognitive', 'confidence', 'social-emotional'],
    materials: ['String (10+ ft)', 'Straw', 'Tape', 'Balloons'],
    setup: 'Thread string through a straw, tie each end to something sturdy (chairs) across the room, pulled tight.',
    steps: [
      'Blow up a balloon (or help the child) and pinch it closed — do not tie it.',
      'Tape the balloon to the straw on the string.',
      'Let go and watch the balloon rocket down the line.',
      'Reset and race again, trying different balloon sizes.',
    ],
    safety: ['Uninflated/popped balloon pieces are a choking hazard — collect scraps immediately'],
    attentionTips: ['A physical "whoosh" and race format re-grabs attention fast', 'Letting the child control the release moment builds anticipation without a long wait'],
    dexterityNotes: 'Blowing up balloons is hard with low hand strength — an adult can blow it up while the child pinches, releases, and tapes.',
  },
  {
    id: 'sci-09', title: 'Oobleck (Cornstarch Goo)', category: 'science',
    ages: ['3-5', '5-7', '7-9'], duration: 20, dexterityFriendly: true,
    benefits: ['sensory-processing', 'self-regulation', 'cognitive'],
    materials: ['2 cups cornstarch', '1 cup water', 'Food coloring (optional)', 'Tray or bin'],
    setup: 'Mix cornstarch and water in a bin until it forms a thick, drippy paste (add water/starch a little at a time).',
    steps: [
      'Let the child squeeze the oobleck slowly and feel it flow like a liquid.',
      'Then have them punch or slap it quickly and feel it turn solid.',
      'Try rolling a ball in the palms — it stays solid until you stop moving.',
      'Talk about how it acts like both a liquid and a solid.',
    ],
    safety: ['Cornstarch mixture is safe if tasted in small amounts but discourage eating', 'Do not pour down the drain — dispose in the trash'],
    attentionTips: ['The strange dual liquid/solid texture is inherently novel and re-engaging on its own', 'Offer a "hit it fast / squeeze it slow" challenge to give structure'],
    dexterityNotes: 'No precise grip needed — whole-hand squeezing and slapping works great for limited dexterity.',
  },
  {
    id: 'sci-10', title: 'Magnet Fishing Hunt', category: 'science',
    ages: ['3-5', '5-7'], duration: 15, dexterityFriendly: true,
    benefits: ['cognitive', 'fine-motor', 'attention'],
    materials: ['Small magnetic wand or magnet fishing pole', 'Mixed objects: some metal (paperclips, washers), some not (buttons, pom-poms)', 'Shallow bin'],
    setup: 'Scatter the mixed objects in a shallow bin.',
    steps: [
      'Ask the child to guess which items the magnet will "catch".',
      'Let them wave the magnet over the bin and see what sticks.',
      'Sort caught vs. not-caught items into two piles.',
      'Talk about what all the "caught" items have in common (metal).',
    ],
    safety: ['Small items like paperclips are choking hazards — supervise closely with younger kids'],
    attentionTips: ['The mystery of "will it stick or not" makes every object a tiny experiment', 'Keep the bin small so success (finding all the metal pieces) feels reachable quickly'],
    dexterityNotes: 'A wand magnet needs only a loose grip and a sweeping motion — no pinching required.',
  },

  // ---------- SENSORY ----------
  {
    id: 'sen-01', title: 'Calm-Down Sensory Bottle', category: 'sensory',
    ages: ['3-5', '5-7', '7-9'], duration: 20, dexterityFriendly: true,
    benefits: ['self-regulation', 'fine-motor', 'confidence'],
    materials: ['Clear plastic bottle with lid', 'Warm water', 'Clear glue or glitter glue', 'Fine glitter', 'Hot glue (adult use only, to seal lid)'],
    setup: 'Fill the bottle about 3/4 with warm water.',
    steps: [
      'Let the child add glitter glue and loose glitter into the bottle.',
      'Top off with warm water, leaving a small air gap.',
      'An adult seals the lid on with hot glue.',
      'Shake and watch the glitter swirl and settle — use as a calm-down tool afterward.',
    ],
    safety: ['Adult must seal the lid so it cannot be opened and glitter/water ingested'],
    attentionTips: ['Making the tool is the activity today; using it becomes a reusable calm-down anchor for other moments', 'Watching glitter settle naturally paces breathing — good bridge into a calm-down routine'],
    dexterityNotes: 'Use a wide-mouth bottle and a funnel so pouring glitter in is easy with an unsteady hand.',
  },
  {
    id: 'sen-02', title: 'Rice Bin Treasure Dig', category: 'sensory',
    ages: ['3-5', '5-7'], duration: 20, dexterityFriendly: true,
    benefits: ['sensory-processing', 'fine-motor', 'attention'],
    materials: ['Large bin', 'Dry rice or dried beans (4–6 cups)', 'Small toys/gems buried inside', 'Scoops and small cups'],
    setup: 'Pour rice into the bin and bury the small toys throughout.',
    steps: [
      'Give the child a scoop and cup and let them dig freely.',
      'Call out one item to find at a time ("find something round").',
      'Move found items into a separate cup to track progress.',
      'When all items are found, bury them again for another round.',
    ],
    safety: ['Rice/beans are a choking hazard for children who mouth objects — supervise closely, not recommended if the child still mouths small items', 'Keep bin on a mat to contain spillover'],
    attentionTips: ['One "find this" call at a time keeps the huge bin from feeling overwhelming', 'Digging is rhythmic and repetitive, which many kids find naturally regulating'],
    dexterityNotes: 'A large scoop needs only a whole-hand grip; skip tweezers/tongs if fine motor control is limited.',
  },
  {
    id: 'sen-03', title: 'Texture Nature Walk & Match', category: 'sensory',
    ages: ['3-5', '5-7', '7-9'], duration: 25, dexterityFriendly: true,
    benefits: ['sensory-processing', 'gross-motor', 'language'],
    materials: ['Small basket or bag', 'A simple texture checklist card (rough, smooth, soft, bumpy)'],
    setup: 'Prepare a short card with 4 texture words and a picture for each.',
    steps: [
      'Walk together outside (or around the room with natural objects available).',
      'For each texture word, find and collect one matching object.',
      'Touch and describe each item as it goes into the basket.',
      'Back at the table, sort the collection by texture again.',
    ],
    safety: ['Check collected items for insects/sharp edges before handling', 'Supervise closely near roads or water if walking outdoors'],
    attentionTips: ['Walking adds movement, which helps many ADHD kids focus better than sitting still', 'A short 4-item checklist gives a clear, visible finish line'],
    dexterityNotes: 'A basket rather than a bag makes dropping items in easier than needing to grip and release inside a narrow opening.',
  },
  {
    id: 'sen-04', title: 'Frozen Dinosaur Rescue', category: 'sensory',
    ages: ['3-5', '5-7'], duration: 25, dexterityFriendly: true,
    benefits: ['sensory-processing', 'fine-motor', 'attention'],
    materials: ['Small toy dinosaurs/animals frozen in a block of ice', 'Warm water in a small pitcher', 'Plastic tools (spoons, droppers)', 'Tray'],
    setup: 'Freeze toys in a container of water the night before; unmold into a tray.',
    steps: [
      'Let the child pour warm water over the ice to melt it.',
      'Use a dropper or spoon to work at melted pockets.',
      'Cheer for each dinosaur as it is freed.',
      'Line up rescued dinosaurs by size or color when done.',
    ],
    safety: ['Ice can be slippery on the floor — keep on a tray with a towel underneath'],
    attentionTips: ['The rescue "story" frame (dinosaurs trapped, need saving) adds motivation beyond the sensory input alone', 'Each freed toy is an automatic mini celebration point'],
    dexterityNotes: 'A dropper works with light squeezing; a spoon is easier still for low grip strength.',
  },
  {
    id: 'sen-05', title: 'Scented Playdough Squeeze', category: 'sensory',
    ages: ['3-5', '5-7', '7-9'], duration: 20, dexterityFriendly: true,
    benefits: ['sensory-processing', 'self-regulation', 'fine-motor'],
    materials: ['Soft playdough (store-bought or homemade)', 'A few drops of safe extract (vanilla, mint, lemon) kneaded in', 'Rolling pin', 'Simple cookie cutters'],
    setup: 'Knead a few drops of extract into each color of playdough ahead of time.',
    steps: [
      'Let the child squeeze, roll, and flatten the dough freely for a few minutes.',
      'Introduce cutters to press out simple shapes.',
      'Smell each scented color and guess what it is.',
      'Combine colors/scents to make a "new invention".',
    ],
    safety: ['Not for children who still mouth objects, due to small pieces and scent oils', 'Check for nut- or allergen-based extracts if relevant to the child'],
    attentionTips: ['Open-ended squeezing has no "wrong" outcome, which lowers frustration for kids who tire of instructions', 'Scent adds a second sensory channel that renews interest once squeezing alone gets old'],
    dexterityNotes: 'Soft, warmed dough requires less hand strength; a rolling pin with wide grips helps kids with weaker hands flatten it.',
  },
  {
    id: 'sen-06', title: 'Bubble Wrap Stomp Path', category: 'sensory',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['gross-motor', 'sensory-processing', 'self-regulation'],
    materials: ['Bubble wrap sheets (large bubbles)', 'Tape'],
    setup: 'Tape a path of bubble wrap sheets across the floor.',
    steps: [
      'Invite the child to walk, stomp, or hop along the path.',
      'Try different ways to move: tiptoe, big stomps, slow steps.',
      'Count how many pops happen in one trip.',
      'Flip to a fresh sheet and repeat.',
    ],
    safety: ['Bubble wrap can be slippery on hard floors — tape all edges down firmly'],
    attentionTips: ['Full-body movement plus a satisfying pop sound gives quick sensory payoff for kids who need to move to focus', 'Changing the movement style (stomp/tiptoe/hop) resets novelty without changing the whole activity'],
    dexterityNotes: 'This is a gross-motor, feet-based activity, ideal when hand dexterity is limited.',
  },
  {
    id: 'sen-07', title: 'Water Bead Scoop & Sort', category: 'sensory',
    ages: ['5-7', '7-9'], duration: 20, dexterityFriendly: true,
    benefits: ['sensory-processing', 'fine-motor', 'cognitive'],
    materials: ['Pre-soaked water beads (soak overnight, supervise sourcing — keep away from very young children)', 'Bin', 'Scoops, slotted spoons', 'Sorting cups by color'],
    setup: 'Soak water beads the night before per package instructions; place in a bin.',
    steps: [
      'Let the child scoop beads with a slotted spoon.',
      'Sort scooped beads into cups by color.',
      'Try squeezing a few gently in the palm to feel the texture.',
      'Count how many of each color were found.',
    ],
    safety: ['NOT appropriate for children who mouth objects — water beads are a serious swallowing/choking hazard; adult supervision required at all times', 'Dispose of used beads in trash, not down drains'],
    attentionTips: ['Sorting by color turns open sensory play into a small, achievable task with a visible end point', 'The unusual squishy-slippery texture is highly novel and holds interest well'],
    dexterityNotes: 'A slotted spoon needs only a scoop-and-lift motion, not a pincer grip.',
  },
  {
    id: 'sen-08', title: 'Sound Shaker Match Game', category: 'sensory',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['attention', 'cognitive', 'sensory-processing'],
    materials: ['6 small opaque containers (film canisters or travel bottles) in matching pairs', 'Fillers for each pair: rice, beans, bells, sand, paperclips, cotton balls'],
    setup: 'Fill pairs of containers with the same material so each has a matching shaker sound; seal well.',
    steps: [
      'Mix all 6 shakers up on the table.',
      'Shake one and listen carefully.',
      'Shake others one at a time to find its matching sound partner.',
      'Set matched pairs aside and continue until all pairs are found.',
    ],
    safety: ['Seal containers securely (tape shut) so contents cannot spill out and become a choking hazard'],
    attentionTips: ['A clear win condition (all pairs matched) works well as a short, focused challenge', 'Shaking is a satisfying repetitive motion that can help with self-regulation while thinking'],
    dexterityNotes: 'Use containers with a wide grip; lightweight shakers need very little hand strength to use.',
  },

  // ---------- ART & CRAFT ----------
  {
    id: 'art-01', title: 'Paper Plate Weaving', category: 'art',
    ages: ['5-7', '7-9'], duration: 25, dexterityFriendly: false,
    benefits: ['fine-motor', 'attention', 'cognitive'],
    materials: ['Paper plate with slits pre-cut around the edge', 'Yarn in a few colors', 'Tape for the yarn end'],
    setup: 'Pre-cut 8–10 evenly spaced slits around the plate rim.',
    steps: [
      'Tape one end of yarn to the back of the plate and thread it through a slit.',
      'Guide the child to weave over one slit, under the next, around the plate.',
      'Switch colors partway for a striped effect.',
      'Tie off and trim the end when the plate is full.',
    ],
    safety: ['Pre-cut the slits yourself to avoid scissor use for younger children'],
    attentionTips: ['Break the task into short color "sections" so switching yarn feels like a fresh mini-task', 'The repeating over-under pattern builds a rhythm that helps sustain focus once started'],
    dexterityNotes: 'If threading is hard, tape a large plastic needle or a stiffened yarn end (dip in glue and let dry) to make it easier to push through slits.',
  },
  {
    id: 'art-02', title: 'Bubble Wrap Painting', category: 'art',
    ages: ['3-5', '5-7'], duration: 20, dexterityFriendly: true,
    benefits: ['sensory-processing', 'fine-motor', 'confidence'],
    materials: ['Bubble wrap sheet', 'Washable paint', 'Paper', 'Paint trays or paper plates'],
    setup: 'Cut bubble wrap into hand-sized pieces and pour a little paint into trays.',
    steps: [
      'Press the bubble wrap into the paint, bubble-side down.',
      'Press the painted side onto paper to stamp a textured print.',
      'Try different colors and overlapping prints.',
      'Let dry and admire the finished texture pattern.',
    ],
    safety: ['Use washable, non-toxic paint', 'Supervise closely if the child mouths materials'],
    attentionTips: ['Stamping gives an instant visual result with very little precision needed, which builds quick confidence', 'Offering 2–3 paint colors avoids decision overload while still allowing choice'],
    dexterityNotes: 'Pressing with a flat palm works as well as gripping — good for limited hand strength or coordination.',
  },
  {
    id: 'art-03', title: 'Salt Dough Handprint Keepsake', category: 'art',
    ages: ['3-5', '5-7', '7-9'], duration: 30, dexterityFriendly: true,
    benefits: ['fine-motor', 'self-regulation', 'confidence'],
    materials: ['Salt dough (1 cup flour, 1/2 cup salt, 1/2 cup water, mixed and kneaded)', 'Rolling pin', 'Paint and brushes (for after baking/drying)'],
    setup: 'Mix and knead the dough, then roll it flat to about 1/2 inch thick on a tray.',
    steps: [
      'Press the child\'s hand firmly into the dough to leave a clean print.',
      'Use a straw to poke a hole at the top if it will be hung later.',
      'Air dry for 24–48 hours or bake on low heat (adult only).',
      'Once hardened, let the child paint and decorate it.',
    ],
    safety: ['Oven baking must be done by an adult only', 'Not for children who mouth objects due to raw dough/salt content'],
    attentionTips: ['Splitting this into "make it today, decorate it tomorrow" matches two shorter attention spans instead of one long one', 'The keepsake outcome (a gift, a decoration) gives extra motivation to finish'],
    dexterityNotes: 'A firm, single press is all that is required for the handprint step — very accessible for limited dexterity.',
  },
  {
    id: 'art-04', title: 'Torn Paper Mosaic', category: 'art',
    ages: ['3-5', '5-7'], duration: 20, dexterityFriendly: true,
    benefits: ['fine-motor', 'attention', 'confidence'],
    materials: ['Colored construction paper', 'Glue stick', 'Plain paper with a simple large outline drawn (star, heart, fish)'],
    setup: 'Draw one large, simple shape outline on the base paper.',
    steps: [
      'Tear (not cut) construction paper into small pieces — this is the main activity.',
      'Spread glue inside the outline a small section at a time.',
      'Press torn pieces onto the glued section.',
      'Continue until the whole shape is filled in.',
    ],
    safety: ['No scissors needed — tearing avoids sharp-tool risk entirely'],
    attentionTips: ['Gluing "one small section at a time" breaks a big project into several small, completable steps', 'Tearing paper is a satisfying repetitive motion that can be done without fine precision'],
    dexterityNotes: 'Tearing paper requires only a pinch-and-pull motion, no scissors or precise cutting.',
  },
  {
    id: 'art-05', title: 'Q-tip Dot Constellation Art', category: 'art',
    ages: ['5-7', '7-9'], duration: 20, dexterityFriendly: true,
    benefits: ['fine-motor', 'attention', 'cognitive'],
    materials: ['Dark blue or black paper', 'White and yellow paint', 'Cotton swabs', 'White pencil or crayon (optional, for connecting star lines)'],
    setup: 'Pour a little white and yellow paint into small dishes.',
    steps: [
      'Dip a cotton swab in paint and dot it onto the paper to make a "star".',
      'Repeat, spacing stars across the page to form a constellation.',
      'Optionally connect the dots with a white pencil to form a shape.',
      'Add a title to the finished night-sky picture.',
    ],
    safety: ['Use washable paint', 'Supervise near paint to avoid ingestion'],
    attentionTips: ['Each dot is a tiny, fast, low-effort action, so progress feels quick even with a short attention span', 'Letting the child invent their own constellation shape adds ownership to the task'],
    dexterityNotes: 'A cotton swab needs only a light dabbing motion — much easier than a paintbrush for shaky or weak grips.',
  },
  {
    id: 'art-06', title: 'Nature Collage Frame', category: 'art',
    ages: ['5-7', '7-9'], duration: 25, dexterityFriendly: false,
    benefits: ['gross-motor', 'fine-motor', 'cognitive'],
    materials: ['Cardboard frame (cut a rectangle with a rectangle hole in the middle)', 'Collected leaves, petals, twigs', 'Glue', 'Yarn for hanging'],
    setup: 'Pre-cut a sturdy cardboard frame shape.',
    steps: [
      'Go on a short walk to collect natural items (or use a prepared basket).',
      'Arrange items on the frame before gluing anything down.',
      'Once happy with the layout, glue pieces one at a time.',
      'Attach a yarn loop on the back once dry for hanging.',
    ],
    safety: ['Check collected natural items for insects and rinse if needed', 'Supervise glue use'],
    attentionTips: ['Arranging before gluing gives room to change their mind without "ruining" anything, which lowers pressure', 'Combining a walk (movement) with a craft (sit-down task) balances energy levels'],
    dexterityNotes: 'Use a glue stick instead of liquid glue, and pre-collect larger natural items that are easy to place with a whole hand.',
  },
  {
    id: 'art-07', title: 'Paper Bag Puppet', category: 'art',
    ages: ['3-5', '5-7'], duration: 25, dexterityFriendly: true,
    benefits: ['fine-motor', 'social-emotional', 'language'],
    materials: ['Small paper lunch bag', 'Markers or crayons', 'Yarn scraps, googly eyes, stickers', 'Glue stick'],
    setup: 'Lay the paper bag flat with the folded bottom facing up (this becomes the mouth).',
    steps: [
      'Decorate the bag as a face or animal using markers.',
      'Glue on yarn hair, googly eyes, or stickers for extra texture.',
      'Once dry, put a hand inside to make the puppet "talk".',
      'Put on a 1-minute puppet show together.',
    ],
    safety: ['Supervise use of small decorative pieces like googly eyes if the child mouths objects'],
    attentionTips: ['The end goal (a puppet that performs) gives a clear, motivating reason to finish decorating', 'Performing the mini puppet show afterward rewards the sit-down craft time with movement and play'],
    dexterityNotes: 'Stickers are an easy substitute for gluing small pieces if pinching glue-covered items is difficult.',
  },
  {
    id: 'art-08', title: 'Sponge Stamp Garden', category: 'art',
    ages: ['3-5', '5-7'], duration: 20, dexterityFriendly: true,
    benefits: ['fine-motor', 'sensory-processing', 'confidence'],
    materials: ['Sponges cut into flower/leaf shapes', 'Washable paint', 'Large paper', 'Clothespins (attach to sponge as a handle)'],
    setup: 'Clip a clothespin to the back of each sponge shape as an easy-grip handle.',
    steps: [
      'Dip the sponge into paint.',
      'Press firmly onto the paper to stamp a flower or leaf.',
      'Repeat across the page to "grow a garden".',
      'Add stems or a sun with a marker once the paint dries.',
    ],
    safety: ['Use washable, non-toxic paint'],
    attentionTips: ['Filling a whole page with repeated stamps gives a big, satisfying visual payoff for low effort per stamp', 'The clothespin handle removes the fine-motor barrier so the child can focus on the fun part'],
    dexterityNotes: 'The clothespin handle means no direct grip on a wet, slippery sponge is needed.',
  },

  // ---------- MOVEMENT ----------
  {
    id: 'mov-01', title: 'Animal Walk Relay', category: 'movement',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['gross-motor', 'self-regulation', 'attention'],
    materials: ['Open floor space', 'Printed or drawn animal cards (optional)'],
    setup: 'Mark a start and end point a short distance apart.',
    steps: [
      'Show or name an animal (bear crawl, frog jump, crab walk, snake slither).',
      'The child moves like that animal from start to end.',
      'Switch to a new animal for the way back.',
      'Repeat with 4–5 different animals total.',
    ],
    safety: ['Clear the path of tripping hazards and furniture with sharp corners'],
    attentionTips: ['Frequent switching (every 20–30 seconds) matches short attention spans and keeps novelty high', 'Heavy movement like crawling and jumping can help discharge excess energy before a seated task'],
    dexterityNotes: 'Offer a seated or standing arm-only version (e.g., "eagle arms") for any child who cannot get on the floor.',
  },
  {
    id: 'mov-02', title: 'Balloon Volleyball', category: 'movement',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['gross-motor', 'attention', 'cognitive'],
    materials: ['One balloon', 'Optional: string across the middle of the room as a "net"'],
    setup: 'Blow up a balloon and clear a small open space.',
    steps: [
      'Tap the balloon back and forth, trying not to let it touch the ground.',
      'Count out loud how many taps in a row.',
      'Try tapping with the other hand, or with elbows for variety.',
      'Reset the count each time it drops and try to beat the record.',
    ],
    safety: ['Popped balloon pieces are a choking hazard — remove immediately if it pops'],
    attentionTips: ['The slow-falling balloon gives extra reaction time versus a ball, building success and confidence', 'Counting the streak creates a simple, motivating personal goal'],
    dexterityNotes: 'Works seated in a chair for children with limited mobility or dexterity — a light balloon is easy to tap even with an open palm.',
  },
  {
    id: 'mov-03', title: 'Freeze Dance with Visual Cues', category: 'movement',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['gross-motor', 'self-regulation', 'attention'],
    materials: ['Music player', 'A red "stop" card and green "go" card'],
    setup: 'Have music ready and the two cue cards in hand.',
    steps: [
      'Play music and dance freely while the green card is shown.',
      'Hold up the red card and pause the music — everyone freezes.',
      'Hold the freeze for a few seconds, then flip back to green.',
      'Repeat, varying how long each round lasts.',
    ],
    safety: ['Clear the dance space of obstacles'],
    attentionTips: ['Visual (not just verbal) stop/go cues make transitions clearer for kids who need extra processing time', 'Freezing briefly acts as a built-in micro-break that resets focus before the next round'],
    dexterityNotes: 'Fully inclusive of any mobility level — dancing can mean arm movement only, from a seated position.',
  },
  {
    id: 'mov-04', title: 'Soft Obstacle Course', category: 'movement',
    ages: ['3-5', '5-7'], duration: 20, dexterityFriendly: false,
    benefits: ['gross-motor', 'cognitive', 'confidence'],
    materials: ['Couch cushions', 'Hula hoop or rope', 'Soft tunnel or table to crawl under', 'Bean bag'],
    setup: 'Arrange 4–5 stations in a simple loop: step over cushions, crawl under a table, step through a hoop, carry a bean bag to a basket.',
    steps: [
      'Walk the course together once slowly, naming each station.',
      'Let the child go through independently while you cheer at each station.',
      'Time it for fun (not for pressure) and try again to "beat" the time.',
      'Rearrange stations for a fresh course.',
    ],
    safety: ['Use only soft materials at floor level — no hard or sharp obstacles', 'Supervise crawling and climbing at all times'],
    attentionTips: ['A physical course with a clear path keeps the goal concrete and visible the whole time', 'Rearranging the same stations gives a "new" course with almost no extra prep'],
    dexterityNotes: 'Skip any station that requires precise grip; carrying a bean bag in two hands or a basket avoids pinch-grip demands.',
  },
  {
    id: 'mov-05', title: 'Bean Bag Toss Target', category: 'movement',
    ages: ['5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['gross-motor', 'fine-motor', 'cognitive'],
    materials: ['2–3 bean bags', 'Bucket, hoop, or taped target on the floor'],
    setup: 'Place the target a short, easily-reachable distance away.',
    steps: [
      'Take turns tossing bean bags toward the target.',
      'Move the target closer or farther to adjust the challenge.',
      'Count successful hits out of a set number of tries.',
      'Try tossing with the non-dominant hand for a fresh challenge.',
    ],
    safety: ['Use soft bean bags only, never hard balls, in indoor spaces'],
    attentionTips: ['Adjustable distance means every child can find a "just right" challenge level and keep succeeding', 'Short rounds of 3–5 tosses keep each turn brief and repeatable'],
    dexterityNotes: 'Bean bags are easier to grip and throw than balls; a large soft target increases the success rate for less-precise throws.',
  },
  {
    id: 'mov-06', title: 'Yoga Pose Story', category: 'movement',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['gross-motor', 'self-regulation', 'language'],
    materials: ['Yoga mat or soft rug', 'Simple pose picture cards (optional)'],
    setup: 'Choose a short story theme (a trip to the jungle, the beach, outer space).',
    steps: [
      'Narrate the story slowly, pausing to act out a simple pose for each part (tree pose for a jungle tree, star pose for outer space).',
      'Hold each pose for a few slow breaths.',
      'Let the child suggest what pose comes next in the story.',
      'End lying flat for a 30-second "rest under the stars" moment.',
    ],
    safety: ['Ensure enough clear floor space and a non-slip surface'],
    attentionTips: ['A story frame gives structure and sequence, which helps some ADHD kids track what comes next', 'Slow, held poses paired with breathing help transition energy down after a busy activity'],
    dexterityNotes: 'All poses can be modified to seated versions in a chair for any child with mobility limitations.',
  },
  {
    id: 'mov-07', title: 'Bubble Popping Chase', category: 'movement',
    ages: ['3-5', '5-7'], duration: 15, dexterityFriendly: true,
    benefits: ['gross-motor', 'attention', 'sensory-processing'],
    materials: ['Bubble solution and wand (or bubble machine)'],
    setup: 'Clear an open indoor or outdoor space.',
    steps: [
      'Blow a stream of bubbles into the air.',
      'The child chases and pops as many as they can before they land.',
      'Try popping with different body parts: hands, elbows, one finger.',
      'Take turns being the bubble-blower and the popper.',
    ],
    safety: ['Use tear-free, non-toxic bubble solution', 'Watch footing if outdoors on uneven ground'],
    attentionTips: ['Chasing a moving, unpredictable target is naturally attention-grabbing without needing to explain rules', 'Switching which body part pops bubbles renews interest without changing the activity'],
    dexterityNotes: 'Popping with a whole arm swing or even a foot stomp works — no fine grip required at all.',
  },
  {
    id: 'mov-08', title: 'Follow-the-Footprints Path', category: 'movement',
    ages: ['3-5', '5-7'], duration: 15, dexterityFriendly: true,
    benefits: ['gross-motor', 'cognitive', 'self-regulation'],
    materials: ['Paper footprint cutouts (pre-cut) or chalk if outdoors', 'Tape'],
    setup: 'Tape a winding path of footprints across the floor, alternating actions written or drawn on some (hop, spin, tiptoe).',
    steps: [
      'Walk the path together once to show how it works.',
      'Let the child follow the footprints independently, following any special actions.',
      'Time the walk or simply celebrate reaching the end.',
      'Rearrange footprints into a new path for another round.',
    ],
    safety: ['Tape footprints down firmly to prevent slipping'],
    attentionTips: ['A visible path gives a clear beginning-to-end structure, useful for kids who struggle with open-ended play', 'Action footprints (hop, spin) break up plain walking so attention keeps resetting'],
    dexterityNotes: 'This is a whole-body, feet-based path — no hand dexterity required at all.',
  },

  // ---------- CALM-DOWN / REGULATION ----------
  {
    id: 'calm-01', title: 'Glitter Jar Breathing', category: 'calm',
    ages: ['3-5', '5-7', '7-9'], duration: 10, dexterityFriendly: true,
    benefits: ['self-regulation', 'attention', 'sensory-processing'],
    materials: ['A pre-made glitter/sensory bottle (see Calm-Down Sensory Bottle activity)'],
    setup: 'Have the sealed glitter bottle ready and sit somewhere quiet.',
    steps: [
      'Shake the bottle together.',
      'Breathe in slowly while the glitter swirls, breathe out slowly as it starts to settle.',
      'Watch quietly until the glitter fully settles.',
      'Talk briefly about how their body feels now versus at the start.',
    ],
    safety: ['Ensure the bottle lid is sealed shut (see the sensory bottle activity for adult-sealing step)'],
    attentionTips: ['The falling glitter provides a natural, visual timer for the breath so no counting is required', 'Keep this short (one shake-and-settle cycle) rather than expecting long stillness'],
    dexterityNotes: 'Shaking is a large, easy gross-motor motion suitable for any hand strength.',
  },
  {
    id: 'calm-02', title: 'Squeeze Ball Circuit', category: 'calm',
    ages: ['5-7', '7-9'], duration: 10, dexterityFriendly: true,
    benefits: ['self-regulation', 'fine-motor', 'attention'],
    materials: ['A soft stress ball or stretchy squeeze toy'],
    setup: 'Sit together somewhere calm and quiet.',
    steps: [
      'Squeeze the ball tightly for 5 seconds while breathing in.',
      'Release the squeeze slowly while breathing out.',
      'Repeat for 5–8 rounds, counting together out loud.',
      'Notice out loud how hands feel more relaxed afterward.',
    ],
    safety: ['Choose a ball that cannot be bitten through or that has small parts that could detach'],
    attentionTips: ['Pairing a physical squeeze with counting gives the mind and hands a matched job, reducing wandering focus', 'Keep rounds short and predictable (a fixed count) so the end is always in sight'],
    dexterityNotes: 'A larger, softer ball needs less hand strength; if squeezing is hard, pressing the ball between both palms works just as well.',
  },
  {
    id: 'calm-03', title: 'Weighted Lap Pad Story Time', category: 'calm',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['self-regulation', 'sensory-processing', 'language'],
    materials: ['A weighted lap pad or a folded heavy blanket', 'A favorite short picture book'],
    setup: 'Find a cozy, quiet spot to sit or recline together.',
    steps: [
      'Place the weighted pad across the child\'s lap.',
      'Read the story slowly, pausing to look at pictures together.',
      'Let the child hold or hug the pad while listening.',
      'End with one quiet question about the story.',
    ],
    safety: ['Do not exceed a safe weight for the child\'s size (roughly 10% of body weight is a common guideline) — check with a caregiver/OT if unsure', 'Never place a weighted item over the face or neck'],
    attentionTips: ['Gentle deep pressure can help some kids settle enough to sit through a short story', 'Keep the book short and highly familiar to reduce cognitive load during a calm-down moment'],
    dexterityNotes: 'No hand skills required — this is a listening and resting activity.',
  },
  {
    id: 'calm-04', title: 'Bubble Breathing Break', category: 'calm',
    ages: ['3-5', '5-7', '7-9'], duration: 10, dexterityFriendly: true,
    benefits: ['self-regulation', 'gross-motor', 'attention'],
    materials: ['Bubble solution and wand'],
    setup: 'Sit or stand together somewhere with a little open space.',
    steps: [
      'Take a slow breath in through the nose.',
      'Blow out slowly and gently to make one big bubble (fast breath pops it right away).',
      'Watch the bubble float and land.',
      'Repeat for 5–6 slow bubbles.',
    ],
    safety: ['Use tear-free, non-toxic bubble solution', 'Supervise so solution is not swallowed'],
    attentionTips: ['Bubbles make invisible breath visible, giving immediate feedback on whether the breath was slow enough', 'The natural goal of "make it big, not pop it" motivates a genuinely slower breath without needing to explain the concept'],
    dexterityNotes: 'A large-handled bubble wand is easier to hold steady than a small one.',
  },
  {
    id: 'calm-05', title: 'Five Senses Grounding Hunt', category: 'calm',
    ages: ['5-7', '7-9'], duration: 10, dexterityFriendly: true,
    benefits: ['self-regulation', 'cognitive', 'language'],
    materials: ['None required — can use a simple printed checklist as a visual aid'],
    setup: 'Sit together somewhere calm, ideally with a view of the room or outside.',
    steps: [
      'Name 5 things you can see.',
      'Name 4 things you can touch nearby.',
      'Name 3 things you can hear.',
      'Name 2 things you can smell, and 1 thing you can taste (or like the taste of).',
    ],
    safety: ['None specific — a purely verbal/observational activity'],
    attentionTips: ['The countdown structure (5-4-3-2-1) gives a clear, short, predictable path to the end', 'Works well as a de-escalation tool right after a high-energy activity, before returning to seated work'],
    dexterityNotes: 'No materials or hand skills required at all.',
  },
  {
    id: 'calm-06', title: 'Slow Motion Statue Game', category: 'calm',
    ages: ['3-5', '5-7', '7-9'], duration: 10, dexterityFriendly: true,
    benefits: ['self-regulation', 'gross-motor', 'attention'],
    materials: ['Open floor space', 'Music (optional)'],
    setup: 'Clear a small space to move in.',
    steps: [
      'Call out an action (waving, jumping, spinning) done at normal speed.',
      'Then call "slow motion!" and repeat the same action as slowly as possible.',
      'Alternate between normal and slow motion every 15–20 seconds.',
      'End on a slow-motion freeze, held for a few breaths.',
    ],
    safety: ['Clear the space of obstacles', 'Keep normal-speed bursts brief to avoid overstimulation before the calm-down goal'],
    attentionTips: ['Deliberately slowing movement helps the body practice down-regulating after high energy', 'The game format (a clear "slow motion!" cue) makes the transition into calm feel like part of the fun, not a demand to stop'],
    dexterityNotes: 'Any movement style works, including seated or arm-only versions.',
  },

  // ---------- FINE MOTOR ----------
  {
    id: 'fine-01', title: 'Pom-Pom Tong Transfer', category: 'fine',
    ages: ['3-5', '5-7'], duration: 15, dexterityFriendly: false,
    benefits: ['fine-motor', 'attention', 'confidence'],
    materials: ['Large pom-poms', 'Child-friendly tongs or tweezers', 'Ice cube tray or muffin tin'],
    setup: 'Pour pom-poms into one bowl and place the empty tray nearby.',
    steps: [
      'Show how to squeeze the tongs to pick up one pom-pom.',
      'Move it across and drop it into one tray slot.',
      'Repeat, trying to fill every slot.',
      'Sort by color into different rows if desired.',
    ],
    safety: ['Pom-poms are a choking hazard for children who mouth objects — supervise closely'],
    attentionTips: ['Filling a fixed number of tray slots gives a visible, countable goal', 'This activity directly builds the pincer-grip strength that many other tasks need — track small improvements over weeks as their own win'],
    dexterityNotes: 'If tongs are too hard, start with fingers only, or use wider "easy-grip" training tongs designed for small hands.',
  },
  {
    id: 'fine-02', title: 'Lacing Cards', category: 'fine',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: false,
    benefits: ['fine-motor', 'attention', 'cognitive'],
    materials: ['Sturdy cardboard shape with pre-punched holes', 'Shoelace or yarn with a stiffened tip'],
    setup: 'Punch large, widely-spaced holes around the edge of a simple cardboard shape.',
    steps: [
      'Show how to push the lace up through one hole and down through the next.',
      'Let the child continue around the shape at their own pace.',
      'Tie off the ends when finished.',
      'Try a new shape or a faster pace next time.',
    ],
    safety: ['Supervise use of laces around the neck — do not leave unattended with a long lace'],
    attentionTips: ['Widely-spaced, large holes keep early success rate high, which matters more than speed for sustained engagement', 'Let the child stop after a partial round if attention fades — resume later rather than forcing completion'],
    dexterityNotes: 'Use very large holes and a stiff-tipped lace (dip the tip in glue and let it dry hard) to make threading much easier.',
  },
  {
    id: 'fine-03', title: 'Clothespin Color Match', category: 'fine',
    ages: ['3-5', '5-7'], duration: 15, dexterityFriendly: false,
    benefits: ['fine-motor', 'cognitive', 'confidence'],
    materials: ['Colored clothespins', 'A paper plate or cup with matching colored dots/stickers around the edge'],
    setup: 'Stick colored dot stickers around the rim of a paper plate.',
    steps: [
      'Show how to squeeze a clothespin open and clip it onto the matching color dot.',
      'Let the child match remaining clothespins to their dots.',
      'Once full, remove them all and mix up the pile to play again.',
      'Time it for fun on a repeat round if motivating.',
    ],
    safety: ['Supervise closely as clothespins can pinch fingers'],
    attentionTips: ['Bright color-matching gives an instant right/wrong signal, which some kids find motivating and clear', 'Keep the total number of clothespins small (6–8) so the task stays short'],
    dexterityNotes: 'Use looser, easier-to-squeeze wooden clothespins rather than stiff plastic ones; large chip clips are an easier alternative.',
  },
  {
    id: 'fine-04', title: 'Playdough Letter Squish', category: 'fine',
    ages: ['3-5', '5-7', '7-9'], duration: 15, dexterityFriendly: true,
    benefits: ['fine-motor', 'cognitive', 'language'],
    materials: ['Playdough', 'Laminated cards with large letters or numbers printed on them'],
    setup: 'Lay a card flat and give the child a ball of playdough.',
    steps: [
      'Flatten a small piece of playdough into a "snake" by rolling.',
      'Press and shape the snake along the lines of the printed letter.',
      'Say the letter sound out loud once it is formed.',
      'Squish it back into a ball and try the next letter.',
    ],
    safety: ['Not for children who mouth objects due to small dough pieces'],
    attentionTips: ['Squishing the dough back into a ball at the end gives a satisfying "reset" between letters, useful for kids who need frequent fresh starts', 'Only introduce 2–3 letters per session to avoid fatigue'],
    dexterityNotes: 'Rolling a snake shape can be done by pressing dough on the table with a flat hand rather than rolling between palms if grip strength is limited.',
  },
  {
    id: 'fine-05', title: 'Bead Threading Necklace', category: 'fine',
    ages: ['5-7', '7-9'], duration: 20, dexterityFriendly: false,
    benefits: ['fine-motor', 'attention', 'confidence'],
    materials: ['Large wooden or plastic beads', 'Pipe cleaner or stiffened lace', 'Tray to keep beads contained'],
    setup: 'Pour beads into a shallow tray and prepare one pipe cleaner per child.',
    steps: [
      'Pick one bead at a time and thread it onto the pipe cleaner.',
      'Continue until the string is comfortably full.',
      'Twist the ends together to form a wearable necklace or bracelet.',
      'Wear or gift the finished piece.',
    ],
    safety: ['Beads are a choking hazard for children who mouth objects — use extra-large beads or supervise very closely'],
    attentionTips: ['A pipe cleaner is stiffer than string, making each thread easier and faster, which keeps momentum going', 'Wearing the finished necklace immediately gives a proud, tangible payoff'],
    dexterityNotes: 'A pipe cleaner\'s rigid tip threads far more easily than floppy string — always prefer it for kids with dexterity challenges.',
  },
  {
    id: 'fine-06', title: 'Sticker Sorting Station', category: 'fine',
    ages: ['3-5', '5-7'], duration: 15, dexterityFriendly: true,
    benefits: ['fine-motor', 'cognitive', 'attention'],
    materials: ['A sheet of assorted stickers', 'Paper divided into labeled sections (shapes, colors, or animals)'],
    setup: 'Draw or print a simple sorting grid with 3–4 labeled sections.',
    steps: [
      'Peel one sticker at a time from the sheet.',
      'Decide which section it belongs in.',
      'Press it into place on the grid.',
      'Continue until the sheet is empty.',
    ],
    safety: ['Supervise closely if the child mouths small sticker backing paper'],
    attentionTips: ['Peeling-and-placing is a short, repeatable two-step action that is easy to restart after a distraction', 'The sorting decision adds a light thinking task without becoming overwhelming'],
    dexterityNotes: 'Pre-peel the corner of each sticker to make lifting them off the sheet much easier for weaker fingers.',
  },

  // ---------- SOCIAL-EMOTIONAL ----------
  {
    id: 'soc-01', title: 'Feelings Face Match', category: 'social',
    ages: ['3-5', '5-7'], duration: 15, dexterityFriendly: true,
    benefits: ['social-emotional', 'language', 'cognitive'],
    materials: ['Cards showing simple faces (happy, sad, angry, surprised, calm)', 'A hand mirror'],
    setup: 'Lay the feeling cards face up on the table.',
    steps: [
      'Hold up one card and name the feeling shown.',
      'Look in the mirror and try making that same face.',
      'Talk about a time they felt that way.',
      'Repeat through all the cards, mixing up the order each round.',
    ],
    safety: ['None specific'],
    attentionTips: ['Mirroring a face is quick, physical, and playful, which keeps a "talking about feelings" activity from feeling like a lecture', 'Keep to 4–5 cards per session rather than a large deck to avoid losing steam'],
    dexterityNotes: 'No hand skills required beyond holding a card, which any grip level can manage.',
  },
  {
    id: 'soc-02', title: 'Kindness Bingo', category: 'social',
    ages: ['5-7', '7-9'], duration: 25, dexterityFriendly: true,
    benefits: ['social-emotional', 'self-regulation', 'confidence'],
    materials: ['A simple 3x3 grid with one kind action drawn/written per square (share a toy, say thank you, help clean up, give a compliment)', 'Marker or stickers to mark squares'],
    setup: 'Prepare the grid ahead of time with age-appropriate kind actions.',
    steps: [
      'Explain that any time they do one of the actions, they mark that square.',
      'Keep the board visible during the day/session as opportunities come up.',
      'Celebrate together when a row or the whole board is marked.',
      'Reset the board for a new set of actions next time.',
    ],
    safety: ['None specific'],
    attentionTips: ['Spreading marks across a whole day (not one sitting) matches real attention span far better than an in-one-go activity', 'A visible board acts as an ongoing reminder without needing constant verbal prompts'],
    dexterityNotes: 'Use large stickers instead of a marker if a precise checkmark is difficult to make.',
  },
  {
    id: 'soc-03', title: 'Turn-Taking Bridge Build', category: 'social',
    ages: ['3-5', '5-7', '7-9'], duration: 20, dexterityFriendly: true,
    benefits: ['social-emotional', 'fine-motor', 'self-regulation'],
    materials: ['Building blocks (large, easy-grip blocks work best)', 'A small toy car or figure to cross the finished bridge'],
    setup: 'Clear a flat space to build on.',
    steps: [
      'Explain the goal: build a bridge together, one piece at a time, taking turns.',
      'Each person adds exactly one block on their turn, then says "your turn".',
      'Continue until the bridge is finished (or reaches an agreed height/length).',
      'Send the toy car across the finished bridge together to celebrate.',
    ],
    safety: ['Use blocks free of small detachable parts if the child mouths objects'],
    attentionTips: ['One block per turn keeps waiting periods short, which is easier to tolerate than watching someone build for a long stretch', 'A clear finish condition (car crosses the bridge) gives the shared goal real closure'],
    dexterityNotes: 'Use large, chunky blocks that are easy to stack even with limited grip strength.',
  },
  {
    id: 'soc-04', title: 'Mirror Me Partner Game', category: 'social',
    ages: ['3-5', '5-7', '7-9'], duration: 10, dexterityFriendly: true,
    benefits: ['social-emotional', 'self-regulation', 'attention'],
    materials: ['None required'],
    setup: 'Stand or sit facing each other with a little space.',
    steps: [
      'One person is the "leader" and makes a slow, simple movement (raise an arm, tilt head).',
      'The other person mirrors it as closely as possible, like a reflection.',
      'Switch leader roles after several movements.',
      'Try slow-motion mirroring for an extra calming challenge.',
    ],
    safety: ['None specific'],
    attentionTips: ['This builds eye contact and attention-to-others gently, through play rather than direct instruction', 'Short turns (a handful of movements each) keep both roles brief and balanced'],
    dexterityNotes: 'Any movement counts, including facial expressions only, for a child with limited body mobility.',
  },
];
